services:
  poll:
    build: ./poll
    ports:
      - "5000:80"
    networks:
      - poll-tier
    env_file:
      - .env
    depends_on:
      - redis

  result:
    build: ./result
    ports:
      - "5001:80"
    networks:
        - result-tier
    env_file:
      - .env
    depends_on:
      - db

  worker:
    build: ./worker
    ports:
      - "80:80"
    networks:
      - worker-tier
    depends_on:
      - redis
      - db
    env_file:
      - .env

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
        - poll-tier
        - worker-tier

  db:
    image: "postgres:alpine"
    ports:
        - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    env_file:
      - .env
    networks:
        - worker-tier
        - result-tier
volumes:
  db-data:

networks:
  poll-tier:
  worker-tier:
  result-tier:
